# Generated by Django 4.1 on 2023-02-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statut', related_query_name='statut', to='auctions.listing'),
        ),
    ]
