# Generated by Django 4.1 on 2023-02-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_statut_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', related_query_name='wishlist', to='auctions.listing'),
        ),
    ]
