# Generated by Django 4.1 on 2023-02-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_wishlist_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statut',
        ),
    ]
