# Generated by Django 4.1 on 2023-02-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='statut',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Statut',
        ),
    ]
