# Generated by Django 4.1 on 2023-02-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='win',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
