# Generated by Django 4.1 on 2023-05-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
